from config import settings as _s

# Exchange / API
API_KEY = _s.API_KEY
API_SECRET = _s.API_SECRET
USE_TESTNET = _s.USE_TESTNET
DRY_RUN = _s.DRY_RUN

# Risk / sizing
POSITION_SIZE_PERCENT = _s.POSITION_SIZE_PERCENT
MAX_OPEN_TRADES = _s.MAX_OPEN_TRADES
DAILY_PROFIT_TARGET = _s.DAILY_PROFIT_TARGET_USD
MAX_INVESTMENT = _s.MAX_INVESTMENT
CAPITAL_MAX_USDT = _s.CAPITAL_MAX_USDT
RISK_REWARD_RATIO = _s.RISK_REWARD_RATIO
MAX_DAILY_DRAWDOWN = _s.MAX_DAILY_DRAWDOWN

# Trading / universe
TRADING_PAIRS = _s.TRADING_PAIRS
TIMEFRAME = _s.TIMEFRAME
MIN_NOTIONAL_USD = _s.MIN_NOTIONAL_USD
MAX_ACTIVE_SYMBOLS = _s.MAX_ACTIVE_SYMBOLS
MAX_SYMBOLS = _s.MAX_SYMBOLS
MIN_24H_VOLUME_USDT = _s.MIN_24H_VOLUME_USDT
SLEEP_SECONDS_BETWEEN_CYCLES = _s.SLEEP_SECONDS_BETWEEN_CYCLES
LEVERAGE = _s.LEVERAGE
MARGIN_MODE = _s.MARGIN_MODE

# Telegram
TELEGRAM_BOT_TOKEN = _s.TELEGRAM_BOT_TOKEN
TELEGRAM_CHAT_ID = _s.TELEGRAM_CHAT_ID

# Logging
LOG_LEVEL = _s.LOG_LEVEL

# Paths
DATA_DIR = _s.DATA_DIR
LOGS_DIR = _s.LOGS_DIR

DAILY_PROFIT_TARGET_USD = DAILY_PROFIT_TARGET
