# Conservative Scalping Profile for Crypto Trading Bot
# This plan provides a safe, testnet-ready configuration with liquidity-aware symbol selection

profile_name: "conservative_scalping"
mode: "live_testnet"  # paper | live_testnet | live_mainnet

universe:
  mode: "dynamic"  # dynamic | static
  static_symbols: ["BTC/USDT", "ETH/USDT", "BNB/USDT", "SOL/USDT", "XRP/USDT", "DOGE/USDT"]
  exclude_symbols: []
  timeframe: "5m"
  dynamic_selector:
    enabled: true
    refresh_interval_min: 30
    min_quote_volume_24h_usdt: 300000000  # 300M USDT minimum volume
    max_spread_bps: 2  # Maximum 2 basis points spread
    min_depth_usdt_within_5bps: 50000  # Minimum 50k USDT depth within 5bps
    min_rvol_1m_bps: 10  # Minimum realized volatility 10 basis points
    max_symbols: 10
    correlation:
      window_min: 720  # 12 hours correlation window
      max_avg_corr: 0.75  # Maximum average correlation

risk:
  position_size_pct: 0.5  # 0.5% of equity per position
  max_risk_per_trade_pct: 0.5  # 0.5% maximum risk per trade
  max_daily_loss_pct: 2.0  # 2% maximum daily loss
  max_concurrent_positions: 3
  leverage: 5
  margin_mode: "ISOLATED"
  respect_exchange_filters: true

sl_tp:
  sl_pct: 0.20  # 0.20% stop loss
  tp_pct: 0.40  # 0.40% take profit  
  trailing_sl:
    enabled: false
    trail_pct: 0.15

execution:
  working_type: "CONTRACT_PRICE"
  reduce_only_brackets: true
  time_in_force: "GTC"

alerts:
  telegram_enabled: true
  notify_on: ["entry", "exit", "sl_tp_set", "error"]